/**
 * 動物のドット絵（tools/sprites.mjs が assets/fauna/*.png から作る。手で編集しない）。
 * rgba は base64 の RGBA8。透明の余白は刈り済みなので、板の高さ＝絵の高さでよい。
 */

const B64 = typeof atob === 'function'
  ? (s) => { const b = atob(s); const u = new Uint8Array(b.length); for (let i = 0; i < b.length; i++) u[i] = b.charCodeAt(i); return u; }
  : (s) => new Uint8Array(Buffer.from(s, 'base64'));

const RAW = {
  ornithischian: { w: 15, h: 7, rgba: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzVpL/81aS/8AAAAAAAAAAAAAAAAAAAAAAAAAAIB0W/+AdFv/gHRb/4B0W/+AdFv/gHRb/4B0W/+AdFv/xVdI/8VXSP8AAAAAe29X/3tvV/97b1f/e29X/3tvV/97b1f/e29X/3tvV/97b1f/e29X/3tvV/97b1f/e29X/3tvV/8AAAAAdWpT/3VqU/91alP/dWpT/3VqU/91alP/dWpT/3VqU/91alP/dWpT/3VqU/91alP/dWpT/3VqU/8YFhT/AAAAAAAAAAAAAAAAAAAAAAAAAABwZU//AAAAAAAAAAAAAAAAAAAAAHBlT/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABrYEz/AAAAAAAAAAAAAAAAAAAAAGtgTP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmXEj/AAAAAAAAAAAAAAAAAAAAAGZcSP8AAAAAAAAAAAAAAAAAAAAA' },
  plesiosaur: { w: 16, h: 6, rgba: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIV4X/+FeF//hXhf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH9zWv9/c1r/f3Na/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHltVv95bVb/eW1W/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHNoUf9zaFH/c2hR/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1iTf9tYk3/bWJN/21iTf9tYk3/bWJN/21iTf9tYk3/bWJN/wAAAAAAAAAAAAAAAAAAAABmXEn/ZlxJ/2ZcSf9mXEn/ZlxJ/2ZcSf9mXEn/ZlxJ/2ZcSf9mXEn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' },
  pterosaur: { w: 16, h: 4, rgba: 'AAAAAAAAAAAAAAAAAAAAAAAAAACFeF//hXhf/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADNWkv/zVpL/wAAAAAAAAAAAAAAAAAAAAB8cFj/fHBY/3xwWP98cFj/fHBY/3xwWP98cFj/fHBY/3xwWP98cFj/vlRG/75URv9zaFH/c2hR/3NoUf9zaFH/c2hR/3NoUf9zaFH/c2hR/3NoUf9zaFH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAal9L/2pfS/9qX0v/al9L/2pfS/9qX0v/al9L/2pfS/9qX0v/al9L/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==' },
  sauropod: { w: 15, h: 6, rgba: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACFeF//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH9zWv9/c1r/AAAAAAAAAAAAAAAAAAAAAHltVv95bVb/eW1W/3ltVv95bVb/eW1W/3ltVv95bVb/eW1W/3ltVv8AAAAAc2hR/3NoUf9zaFH/c2hR/wAAAAAAAAAAc2hR/3NoUf9zaFH/c2hR/3NoUf9zaFH/c2hR/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG1iTf8AAAAAAAAAAG1iTf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZcSf8AAAAAAAAAAGZcSf8AAAAAAAAAAAAAAAAAAAAA' },
  theropod: { w: 16, h: 7, rgba: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzVpL/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIB0W/+AdFv/gHRb/4B0W/+AdFv/gHRb/4B0W/+AdFv/gHRb/4B0W/+AdFv/gHRb/wAAAAB7b1f/e29X/3tvV/97b1f/e29X/3tvV/97b1f/e29X/3tvV/97b1f/e29X/3tvV/97b1f/e29X/3tvV/+8U0X/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1alP/dWpT/wAAAAB1alP/dWpT/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcGVP/3BlT/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGtgTP9rYEz/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmXEj/ZlxI/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==' },
};

/** { w, h, data:RGBA } を返す。base64 の展開は初回だけ */
const cache = new Map();
export function sprite(key) {
  if (!cache.has(key)) {
    const r = RAW[key];
    if (!r) return null;
    cache.set(key, { w: r.w, h: r.h, data: B64(r.rgba) });
  }
  return cache.get(key);
}

export const SPRITE_KEYS = Object.keys(RAW);
